use this C:\Users\aksha\Downloads\table.csv

In [2]:
import pandas as pd

ed = pd.read_csv(r"C:\Users\aksha\OneDrive\Documents\Tableew.csv")


ed = ed.dropna(thresh=4)
ed

,Employee ID,Name,Department,Position,Join Date,Salary (USD)
0,E001,Alice Johnson,Engineering,Software Engineer,15/03/2021,85000.0
1,E002,Bob Smith,Marketing,Marketing Manager,22/07/2019,72000.0
2,E003,Carol Williams,Finance,Financial Analyst,8/11/2020,68000.0
3,E004,David Brown,Engineering,Senior Developer,30/01/2018,95000.0
4,E005,Emma Davis,HR,HR Specialist,12/05/2022,58000.0
5,E006,Frank Miller,Sales,Sales Executive,3/09/2021,62000.0
6,E007,Grace Lee,Engineering,QA Engineer,18/04/2020,70000.0
7,E008,Henry Wilson,Finance,Accountant,1/12/2019,65000.0

In [2]:
#Note csv files are mainly tabular

In [3]:
#we can also use this application to make minor changes like dropping neccessary rows

In [4]:
df = pd.read_excel("table_with_subtext.xlsx", skiprows=2)
df

,Employee ID,Name,Department,Position,Join Date,Salary (USD)
0,E001,Alice Johnson,Engineering,Software Engineer,2021-03-15,85000
1,E002,Bob Smith,Marketing,Marketing Manager,2019-07-22,72000
2,E003,Carol Williams,Finance,Financial Analyst,2020-11-08,68000
3,E004,David Brown,Engineering,Senior Developer,2018-01-30,95000
4,E005,Emma Davis,HR,HR\nSpecialist,2022-05-12,58000
5,E006,Frank Miller,Sales,Sales Executive,2021-09-03,62000
6,E007,Grace Lee,Engineering,QA Engineer,2020-04-18,70000
7,E008,Henry Wilson,Finance,Accountant,2019-12-01,65000

In [5]:
from docx import Document
import pandas as pd

doc = Document(r"C:\Users\aksha\Downloads\tablee.docx")
table = doc.tables[0]

data = [[cell.text for cell in row.cells] for row in table.rows]
Df = pd.DataFrame(data[1:], columns=data[0])   
Df

,Employee ID,Name,Department,Position,Join Date,Salary (USD)
0,E001,Alice Johnson,Engineering,Software Engineer,2021-03-15,85000
1,E002,Bob Smith,Marketing,Marketing Manager,2019-07-22,72000
2,E003,Carol Williams,Finance,Financial Analyst,2020-11-08,68000
3,E004,David Brown,Engineering,Senior Developer,2018-01-30,95000
4,E005,Emma Davis,HR,HR Specialist,2022-05-12,58000
5,E006,Frank Miller,Sales,Sales Executive,2021-09-03,62000
6,E007,Grace Lee,Engineering,QA Engineer,2020-04-18,70000
7,E008,Henry Wilson,Finance,Accountant,2019-12-01,65000

C:/Users/aksha/Downloads/employee_tables.pdf

In [6]:
import pdfplumber
import pandas as pd

with pdfplumber.open("employee_tables.pdf") as pdf:
    page = pdf.pages[0]
    tables = page.extract_tables()   



chosen_table = tables[0]          

#
pdf = pd.DataFrame(chosen_table[1:], columns=chosen_table[0])
pdf

,Employee\nID,Name,Department,Position,Join Date,Salary\n(USD)
0,E001,Alice Johnson,Engineering,Software Engineer,2021-03-15,85000
1,E002,Bob Smith,Marketing,Marketing Manager,2019-07-22,72000
2,E003,Carol Williams,Finance,Financial Analyst,2020-11-08,68000
3,E004,David Brown,Engineering,Senior Developer,2018-01-30,95000
4,E005,Emma Davis,HR,HR Specialist,2022-05-12,58000
5,E006,Frank Miller,Sales,Sales Executive,2021-09-03,62000
6,E007,Grace Lee,Engineering,QA Engineer,2020-04-18,70000
7,E008,Henry Wilson,Finance,Accountant,2019-12-01,65000

In [7]:
chosen_table = tables[1]          


pdf = pd.DataFrame(chosen_table[1:], columns=chosen_table[0])
pdf

,Employee\nID,Name,Department,Position,Join Date,Salary\n(USD)
0,E009,Isabella Garcia,Engineering,DevOps Engineer,2023-02-14,88000
1,E010,Jack Thompson,Marketing,Content Specialist,2022-08-30,61000
2,E011,Karen Patel,Finance,Senior Accountant,2017-06-05,78000
3,E012,Liam Nguyen,Sales,Sales Manager,2020-01-20,92000
4,E013,Mia Rodriguez,HR,Recruitment Lead,2021-11-11,67000
5,E014,Noah Kim,Engineering,Frontend Developer,2023-05-22,81000
6,E015,Olivia Chen,Marketing,Brand Manager,2019-03-17,75000
7,E016,Paul Anderson,Finance,Budget Analyst,2022-12-01,69000

In [1]:
import pandas as pd
from pathlib import Path
from typing import List, Union

def export_tables(
    tables: Union[pd.DataFrame, List[pd.DataFrame]],
    output_path: str,
    file_format: str = "xlsx"  # "xlsx" or "csv"
) -> None:
    """
    Export one or more tables to CSV or Excel.

    Parameters
    ----------
    tables : DataFrame or list of DataFrames
        The extracted & cleaned table(s)
    output_path : str
        Desired output file path (extension will be adjusted if needed)
    file_format : str
        "xlsx" or "csv" (default: "xlsx")
    """

    # Normalize input to a list
    if isinstance(tables, pd.DataFrame):
        tables = [tables]
    
    if not tables:
        print("No tables to export.")
        return

    output_path = Path(output_path)
    file_format = file_format.lower().strip(".")

    # ---------- Excel Export ----------
    if file_format in ["xlsx", "excel"]:
        # Force correct extension
        if output_path.suffix.lower() != ".xlsx":
            output_path = output_path.with_suffix(".xlsx")

        with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
            for i, df in enumerate(tables, start=1):
                sheet_name = f"Table_{i}"
                # Excel sheet name limit is 31 characters
                sheet_name = sheet_name[:31]
                df.to_excel(writer, sheet_name=sheet_name, index=False)

        print(f"Successfully exported {len(tables)} table(s) to → {output_path}")

    # ---------- CSV Export ----------
    elif file_format == "csv":
        if len(tables) == 1:
            # Single table → one CSV file
            if output_path.suffix.lower() != ".csv":
                output_path = output_path.with_suffix(".csv")
            tables[0].to_csv(output_path, index=False, encoding="utf-8-sig")
            print(f"Successfully exported table to → {output_path}")
        else:
            # Multiple tables → create numbered CSV files
            output_dir = output_path.parent / output_path.stem
            output_dir.mkdir(parents=True, exist_ok=True)

            for i, df in enumerate(tables, start=1):
                csv_path = output_dir / f"table_{i}.csv"
                df.to_csv(csv_path, index=False, encoding="utf-8-sig")

            print(f"Successfully exported {len(tables)} tables to folder → {output_dir}")

    else:
        raise ValueError("file_format must be either 'xlsx' or 'csv'")

In [4]:
import pandas as pd
from pathlib import Path
from typing import List, Union

def export_tables(
    tables: Union[pd.DataFrame, List[pd.DataFrame]],
    output_path: str,
    file_format: str = "xlsx"
) -> None:
    if isinstance(tables, pd.DataFrame):
        tables = [tables]
    
    if not tables:
        print("No tables to export.")
        return

    output_path = Path(output_path)
    file_format = file_format.lower().strip(".")

    if file_format in ["xlsx", "excel"]:
        if output_path.suffix.lower() != ".xlsx":
            output_path = output_path.with_suffix(".xlsx")

        with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
            for i, df in enumerate(tables, start=1):
                sheet_name = f"Table_{i}"[:31]
                df.to_excel(writer, sheet_name=sheet_name, index=False)

        print(f"Successfully exported {len(tables)} table(s) to → {output_path}")

    elif file_format == "csv":
        if len(tables) == 1:
            if output_path.suffix.lower() != ".csv":
                output_path = output_path.with_suffix(".csv")
            tables[0].to_csv(output_path, index=False, encoding="utf-8-sig")
            print(f"Successfully exported table to → {output_path}")
        else:
            output_dir = output_path.parent / output_path.stem
            output_dir.mkdir(parents=True, exist_ok=True)

            for i, df in enumerate(tables, start=1):
                csv_path = output_dir / f"table_{i}.csv"
                df.to_csv(csv_path, index=False, encoding="utf-8-sig")

            print(f"Successfully exported {len(tables)} tables to folder → {output_dir}")
    else:
        raise ValueError("file_format must be either 'xlsx' or 'csv'")

In [5]:
#export_tables(tables, "extracted_tables.xlsx", "xlsx") this is the format for exporting

In [6]:
import pdfplumber
import pandas as pd

with pdfplumber.open(r"C:\Users\aksha\Downloads\w27392.pdf") as PDFF:
    page = PDFF.pages[0]
    tables = page.extract_tables()   



chosen_table = tables[0]    

PDFF= pd.DataFrame(chosen_table[1:], columns=chosen_table[0])
PDFF

IndexError: list index out of range

In [9]:
with pdfplumber.open(r"C:\Users\aksha\Downloads\w27392.pdf") as pdf:
    for page_num, page in enumerate(pdf.pages):
        tables = page.extract_tables()
        if tables:                       
            print(f"Page {page_num} has {len(tables)} table(s)")
            pdf

In [10]:
pdf= pd.DataFrame(chosen_table[1:], columns=chosen_table[0])
pdf

NameError: name 'chosen_table' is not defined